function [  ] = fcnTITLE( handle, plotTitle )
%FCNSETTITLE Summary of this function goes here
%   Detailed explanation goes here
text(handle,1,-1/2,...
    plotTitle,...
    'FontSize',18,...
    'FontName','Agency FB',...
    'VerticalAlignment','top');

end

