function [ tPFD2 ] = PlotPFD2( handle )
%PLOTPFD2 Summary of this function goes here
%   Detailed explanation goes here
% Plot SPD and ALT Background Boxes
hold(handle,'on');
text(handle,1,-23.5,'              ',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','middle',...
    'BackgroundColor','k',...
    'LineWidth',1.5,...
    'EdgeColor','y');
text(handle,49.25,-23.5,'              ',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'BackgroundColor','k',...
    'LineWidth',1.5,...
    'EdgeColor','y');

tPFD2.ARSP = text(handle,7,-23.5,'--.-',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','w');

tPFD2.BARO = text(handle,47,-23.5,'---',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','w');
hold(handle,'off');
end

