function [ tPFD2 ] = PlotPFD2( handle )
%PLOTPFD2 Summary of this function goes here
%   Detailed explanation goes here
% Plot SPD and ALT Background Boxes
hold(handle,'on');

% FD - Flight Director (center: 25,-23.5)
tPFD2.FDROLL  = plot(handle,[25 25],-[17 31],'-m','LineWidth',2);
tPFD2.FDPITCH = plot(handle,[17 33],-[23.5 23.5],'-m','LineWidth',2);


% Center White Cross Hair
plot(handle,[23.5 26.5],[-23.5 -23.5],'w-',...
    'LineWidth',2);
plot(handle,[25 25],[-23.5 -22.25],'w-',...
    'LineWidth',2);
% Center White Square
scatter(handle,25,-23.5,'Marker','square',...
     'MarkerEdgeColor',[1 1 1],...
     'MarkerFaceColor',[0 0 0],...
     'LineWidth',2,...
     'SizeData',35);
 
% 
text(handle,1,-23.5,'              ',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','middle',...
    'BackgroundColor','k',...
    'LineWidth',1.5,...
    'EdgeColor','y');
text(handle,46.75,-23.5,'         ',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'BackgroundColor','k',...
    'LineWidth',1.5,...
    'EdgeColor','y');

% ARSP Center Yellow Marker
plot(handle,[9 10],-[23.5 23.5],...
    'LineWidth',2,...
    'Color','y');

% HSI Center Yellow Marker
plot(handle,[25 25],-[38 40.5],...
    'LineWidth',1.5,...
    'Color','y');

tPFD2.ARSP = text(handle,7,-23.5,'--.-',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','g');

tPFD2.BARO = text(handle,46.5,-23.5,'---',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','g');


%% FAIL MODE
% ATT FAIL
tPFD2.FAIL.ATT(1) = patch(handle,30.*[0 1 1 0 0]+10,-27.*[1 1 0 0 1]-10,[0.25 0 0],...
    'EdgeColor',[1 1 1],'LineWidth',1);
tPFD2.FAIL.ATT(2) = plot(handle,30.*[0 1 nan 0 1]+10,-27.*[1 0 nan 0 1]-10,'r',...
    'LineWidth',2);
tPFD2.FAIL.ATT(3) = text(handle,25,-23.5,...
    'ATTITUDE FAIL',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'Color','y',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontWeight','bold');

% ARSP FAIL
tPFD2.FAIL.ARSP(1) = patch(handle,10.*[0 1 1 0 0],-27.*[1 1 0 0 1]-10,[0.25 0 0],...
    'EdgeColor',[1 1 1],'LineWidth',1);
tPFD2.FAIL.ARSP(2) = plot(handle,10.*[0 1 nan 0 1],-27.*[1 0 nan 0 1]-10,'r',...
    'LineWidth',2);
tPFD2.FAIL.ARSP(3) = text(handle,4,-23.5,...
    sprintf('A\nI\nR\nS\nP\nE\nE\nD'),...
    'FontSize',12,...
    'FontName','Agency FB',...
    'Color','y',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontWeight','bold');
tPFD2.FAIL.ARSP(4) = text(handle,6,-23.5,...
    sprintf('F\nA\nI\nL'),...
    'FontSize',12,...
    'FontName','Agency FB',...
    'Color','y',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontWeight','bold');

% ALT FAIL
tPFD2.FAIL.ALT(1) = patch(handle,10.*[0 1 1 0 0]+40,-27.*[1 1 0 0 1]-10,[0.25 0 0],...
    'EdgeColor',[1 1 1],'LineWidth',1);
tPFD2.FAIL.ALT(2) = plot(handle,10.*[0 1 nan 0 1]+40,-27.*[1 0 nan 0 1]-10,'r',...
    'LineWidth',2);
tPFD2.FAIL.ALT(3) = text(handle,44,-23.5,...
    sprintf('A\nL\nT\nI\nT\nU\nD\nE'),...
    'FontSize',12,...
    'FontName','Agency FB',...
    'Color','y',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontWeight','bold');
tPFD2.FAIL.ALT(4) = text(handle,46,-23.5,...
    sprintf('F\nA\nI\nL'),...
    'FontSize',12,...
    'FontName','Agency FB',...
    'Color','y',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontWeight','bold');

% MAG FAIL
tPFD2.FAIL.HDG(1) = patch(handle,30.*[0 1 1 0 0]+10,-6.*[1 1 0 0 1]-39,[0.25 0 0],...
    'EdgeColor',[1 1 1],'LineWidth',1);
tPFD2.FAIL.HDG(2) = plot(handle,30.*[0 1 nan 0 1]+10,-6.*[1 0 nan 0 1]-39,'r',...
    'LineWidth',2);
tPFD2.FAIL.HDG(3) = text(handle,25,-42,...
    'HDG FAIL',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'Color','y',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontWeight','bold');


hold(handle,'off');
end

