function [ tPFD ] = PlotPFD( handle )
%PLOTPFD Summary of this function goes here
%   Detailed explanation goes here

hold(handle,'on');



% Plot TGT ALT BOX
tPFD.TGTALTBOX = text(handle,49.25,-8,'                    ',...
    'FontSize',10,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'BackgroundColor','k',...
    'LineWidth',1.5,...
    'EdgeColor','m');
tPFD2.TGTALTTXT = text(handle,46.5,-8,'---',...
    'FontSize',14,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','m');

% Plot TGT SPD BOX
tPFD.TGTSPDBOX = text(handle,1,-8,'                    ',...
    'FontSize',10,...
    'FontName','Agency FB',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','middle',...
    'BackgroundColor','k',...
    'LineWidth',1.5,...
    'EdgeColor','m');
tPFD.TGTSPDTXT = text(handle,7,-8,'--.-',...
    'FontSize',14,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','m');




text(handle,8,-39.5,'GS',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','w');
tPFD.GS = text(handle,8,-42.5,'---',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','w');


% MODE
tPFD.MODE = text(handle,25,-5,'GUIDED',...
    'FontSize',18,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Color','g',...
    'EdgeColor','g',...
    'LineWidth',1.5,...
    'Margin',4);


hold(handle,'off');

end

