function [ tELEC ] = PlotELEC( handle )
%PLOTELEC Summary of this function goes here
%   Detailed explanation goes here


hold(handle,'on');

plot(handle,[8 8 20 20 8],-[10 22 22 10 10],'w','LineWidth',1);
plot(handle,[30 30 42 42 30],-[10 22 22 10 10],'w','LineWidth',1);

% Battery 1 Status
text(handle,14,-11,'BAT   1',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top');
tELEC.BAT1V = text(handle,16.5,-15,'--.-  V',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
tELEC.BAT1A = text(handle,16.5,-18,'--.-  A',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');

% Battery 2 Status
text(handle,36,-11,'BAT   2',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top');
tELEC.BAT2V = text(handle,38.5,-15,'--.-  V',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
tELEC.BAT2A = text(handle,38.5,-18,'--.-  A',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
%%
a = 2.0;
b = 1.8;
ang=[(0:0.2:2*pi)';0];
cirX=a*cos(ang);
cirY=b*sin(ang);




text(handle,25,-4.5,'MOTOR',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','baseline');

text(handle,25,-27,'SERVO',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top');

tELEC.MOTOR = plot(handle,25+cirX,-7+cirY,...
    '-','LineWidth',2,...
    'Color',[0.5 0.5 0.5]);
tELEC.MOTORON = plot(handle,[23 27],-[7 7],'-g','LineWidth',2,'visible','off');
tELEC.MOTOROFF = plot(handle,[25 25],-[5 9],'-r','LineWidth',2,'visible','off');

tELEC.SERVO = plot(handle,25+cirX,-25+cirY,...
    '-','LineWidth',2,...
    'Color',[0.5 0.5 0.5]);
tELEC.SERVOON = plot(handle,[23 27],-[25 25],'-g','LineWidth',2,'visible','off');
tELEC.SERVOOFF = plot(handle,[25 25],-[23 27],'-r','LineWidth',2,'visible','off');
%%

% BAT1 to ENG ARROW
tELEC.BAT1ARW = plot(handle,[14 14 22 22 23 22 22],-[10 7 7 6 7 8 7],...
    '-','LineWidth',2,...
    'Color',[0.5 0.5 0.5]);

% BAT1 to SERVO ARROW
tELEC.BAT2ARW = plot(handle,[36 36 28 28 27 28 28],-[22 25 25 24 25 26 25],...
    '-','LineWidth',2,...
    'Color',[0.5 0.5 0.5]);










hold(handle,'off');







end






