function [ tSTAT ] = PlotSTAT( handle )
%PLOTTOP Summary of this function goes here
%   Detailed explanation goes here

hold(handle,'on');

%% IMU SELECT BOX
tSTAT.IMU1 = plot(handle,9.5+6.*[0 1 1 0 0],-13.5.*[1 1 0 0 1]-1.5,'-','Color',[0.5 0.5 0.5]);
tSTAT.IMU2 = plot(handle,17+6.*[0 1 1 0 0],-13.5.*[1 1 0 0 1]-1.5,'-','Color',[0.5 0.5 0.5]);


%% IMU Text
text(handle,12.5,-2,'IMU 1',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');

text(handle,20,-2,'IMU 2',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');

text(handle,5,-4,'GPS VEL',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');

text(handle,5,-6,'GPS POS',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');

text(handle,5,-8,'BARO',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');

text(handle,5,-10,'MAG',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');

text(handle,5,-12,'ARSP',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');


%% IMU 1 ERROR PARAMS
tSTAT.SV1 = text(handle,12.5,-4,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

tSTAT.SP1 = text(handle,12.5,-6,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

tSTAT.SH1 = text(handle,12.5,-8,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

tSTAT.SM1 = text(handle,12.5,-10,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

tSTAT.SVT1 = text(handle,12.5,-12,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

%% IMU 2 ERROR PARAMS
tSTAT.SV2 = text(handle,20,-4,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

tSTAT.SP2 = text(handle,20,-6,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

tSTAT.SH2 = text(handle,20,-8,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

tSTAT.SM2 = text(handle,20,-10,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);

tSTAT.SVT2 = text(handle,20,-12,'-.-',...
    'FontSize',12,'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.3 0.3 0.3]);


%%
hold(handle,'off');



end

