function [ tFCTL ] = PlotFCTL( handle )
%PLOTFCTP Summary of this function goes here
%   Detailed explanation goes here

% tFCTL = [];

hold(handle,'on');

% Left Stick Box
tFCTL.LSBOX = plot(handle,15.*[0 0 1 1 0]+8,-14.*[0 1 1 0 0]-26,'-w');
scatter(handle,15.*[0.25 0.75 0.25 0.75]+8,-14.*[0.25 0.25 0.75 0.75]-26,[5 5 5 5],'+w');
% RC RAW CROSS
tFCTL.LSCROSS = scatter(handle,15.5,-33,...
    'CData',[0 1 0],'Marker','+',...
    'SizeData',100,'LineWidth',2);

% Right Stick Box
tFCTL.RSBOX = plot(handle,15.*[0 0 1 1 0]+27,-14.*[0 1 1 0 0]-26,'-w');
scatter(handle,15.*[0.25 0.75 0.25 0.75]+27,-14.*[0.25 0.25 0.75 0.75]-26,[5 5 5 5],'+w');
% RC RAW CROSS
tFCTL.RSCROSS = scatter(handle,34.5,-33,...
    'CData',[0 1 0],'Marker','+',...
    'SizeData',100,'LineWidth',2);


% Servo Travel Track
tFCTL.LAILTRK = plot(handle,[6 6],-[7 15],...
    'Color',[0.5 0.5 0.5],...
    'LineWidth',8);
tFCTL.RAILTRK = plot(handle,[44 44],-[7 15],...
    'Color',[0.5 0.5 0.5],...
    'LineWidth',8);
tFCTL.RUDRTRK = plot(handle,[19 31],-[8 8],...
    'Color',[0.5 0.5 0.5],...
    'LineWidth',9);
tFCTL.ELEVTRK = plot(handle,[33 33],-[13 21],...
    'Color',[0.5 0.5 0.5],...
    'LineWidth',8);

% Servo Travel Limit
plot(handle,[5 7 nan 5 7],-[7 7 nan 15 15],'-','LineWidth',2,'Color',[0 0.75 0]);
plot(handle,[43 45 nan 43 45],-[7 7 nan 15 15],'-','LineWidth',2,'Color',[0 0.75 0]);
plot(handle,[32 34 nan 32 34],-[13 13 nan 21 21],'-','LineWidth',2,'Color',[0 0.75 0]);
plot(handle,[19 19 nan 31 31],-[7 9 nan 7 9],'-','LineWidth',2,'Color',[0 0.75 0]);

% Plane Outline
plot(handle,...
    [5 15 25 35 45],-[11 12 12 12 11],...
    'Color','w','LineWidth',1.5);
plot(handle,[20 30],-[17 17],...
    'Color','w','LineWidth',1.5);
plot(handle,[25 25],-[10 17],...
    'Color','w','LineWidth',1.5);


% Servo Position
tFCTL.LAILPOS = plot(handle,[5 7],-[11 11],'-g','LineWidth',4);
tFCTL.RAILPOS = plot(handle,[43 45],-[11 11],'-g','LineWidth',4);
tFCTL.ELEVPOS = plot(handle,[32 34],-[17 17],'-g','LineWidth',4);
tFCTL.RUDRPOS = plot(handle,[25 25],-[7 9],'-g','LineWidth',4);



% Servo Name
text(handle,6,-16,'L AIL',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');
text(handle,44,-16,'R AIL',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');
text(handle,25,-18,'ELEV',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');
text(handle,25,-1.5,'RUDDER',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');


% Servo Deflection
tFCTL.LAILDEF = text(handle,9,-18,'--.-^{o}--',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
tFCTL.RAILDEF = text(handle,47,-18,'--.-^{o}--',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
tFCTL.ELEVDEF = text(handle,28,-20,'--.-^{o}--',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
tFCTL.RUDRDEF = text(handle,27,-3.5,'--.-^{o}',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');

% RC IN Name
text(handle,12,-40.5,'RUD',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');
text(handle,31,-40.5,'AIL',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');
text(handle,5,-30,'THR',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');
text(handle,45,-30,'ELE',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color','c');

% RC IN PERCENTAGE
tFCTL.RUDPERC = text(handle,20,-40.5,'----%',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
tFCTL.AILPERC = text(handle,39,-40.5,'----%',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
tFCTL.THRPERC = text(handle,7.5,-32.25,'----%',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');
tFCTL.ELEPERC = text(handle,47.5,-32.25,'----%',...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'Color','g');

% % RC IN RAW
tFCTL.RUDRAW = text(handle,17.5,-42.75,'----',...
    'FontSize',10,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.7 0.7 0.7]);
tFCTL.AILRAW = text(handle,36.5,-42.75,'----',...
    'FontSize',10,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.7 0.7 0.7]);
tFCTL.THRRAW = text(handle,5,-34.5,'----',...
    'FontSize',10,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.7 0.7 0.7]);
tFCTL.ELERAW = text(handle,45,-34.5,'----',...
    'FontSize',10,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'Color',[0.7 0.7 0.7]);




hold(handle,'off');


end


