function [ tTOP ] = PlotTOP( handle )
%PLOTTOP Summary of this function goes here
%   Detailed explanation goes here
tTOP.UTC = text(handle, 2,-5.5,'--:--:--',...
    'FontSize',28,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');
text(handle, 2,-8.5,'UTC',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');


tTOP.EST = text(handle, 20,-5.5,'--:--',...
    'FontSize',28,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');
text(handle, 20,-8.5,'EST',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');

tTOP.AIRTIME = text(handle, 33,-5.5,'--:--',...
    'FontSize',28,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');
text(handle, 33,-8.5,'AIR TIME',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');

tTOP.UASTIME = text(handle, 48,-5.5,'----.-',...
    'FontSize',28,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');
text(handle, 48,-8.5,'UAS TIME',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');

tTOP.CAMTIME = text(handle, 63,-5.5,'----.-',...
    'FontSize',28,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');
text(handle, 63,-8.5,'CAM TIME',...
    'FontSize',16,...
    'FontName','Agency FB',...
    'VerticalAlignment','baseline');



end

