function [ tENG ] = PlotENG( handle )
%PLOTENG Summary of this function goes here
%   Detailed explanation goes here



% Throttle Ring
THR = 0;

scale = 6;

a = scale*1.0;
b = scale*0.9;
c = scale*1.01;

s = 1.25;
f = 50;

OX = 15;
OY = -8.5;

ang0  = [(s*pi:-s*pi/f:0)';0];
cirX  = a*cos(ang0)+OX;
cirY  = a*sin(ang0)+OY;

ang   = [(s*pi:-s*pi/4:0)';0];
cirX1 = c*cos(ang)+OX;
cirY1 = c*sin(ang)+OY;

cirX2 = b*cos(ang)+OX;
cirY2 = b*sin(ang)+OY;

cirmarkX = reshape([cirX1,cirX2,nan(6,1)]',[],1);
cirmarkY = reshape([cirY1,cirY2,nan(6,1)]',[],1);

angRing = (s*pi:-s*pi/f*2:s*pi*(1-THR/100))';
THRRINGX = [0;a*cos(angRing);0]+OX;
THRRINGY = [0;a*sin(angRing);0]+OY;

hold(handle,'on')

% Ring Background
tENG.THRRING = fill(handle,nan,nan,[0.5 0.5 0.5]);

% Ring Markers
plot(handle,cirmarkX,cirmarkY,'-','Color',[1 1 1],'LineWidth',2);

% Ring Outline
plot(handle,cirX,cirY,'-','Color',[1 1 1],'LineWidth',1.5);

% Green Line
tENG.THRLINE = plot(handle,[OX THRRINGX(end-1)],[OY THRRINGY(end-1)],'-',...
    'Color',[0.3 0.3 0.3],'LineWidth',2.5);

% Blue Dot
tENG.BLUEDOT = scatter(handle,OX+(a+0.5)*cos(angRing(end)),(OY+(a+0.5)*sin(angRing(end))),'co',...
    'LineWidth',2,'SizeData',15);

text(handle,11.5,-11,sprintf('0'),...
    'FontSize',13,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Color','w');

text(handle,14,-4.75,sprintf('5'),...
    'FontSize',13,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Color','w');

text(handle,19,-8,sprintf('10'),...
    'FontSize',13,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Color','w');


% Throttle Text
text(handle,5,-10.5,sprintf('THR'),...
    'FontSize',14,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Color','w');
text(handle,5,-12.5,sprintf('%%'),...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Color','c');

% BAT mAh Text
text(handle,32,-10.5,sprintf('BAT USED'),...
    'FontSize',14,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Color','w');
text(handle,32,-12.5,sprintf('mAh'),...
    'FontSize',12,...
    'FontName','Agency FB',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Color','c');



% Throttle Text Box
text(handle,16,-11.5,'             ',...
    'FontSize',14,...
    'FontName','Agency FB',...
    'HorizontalAlignment','left',...
    'VerticalAlignment','middle',...
    'EdgeColor','w');


% Throttle Output Percentage
tENG.THRPERC = text(handle,23.5,-11.5,'---.-',...
    'FontSize',18,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','g');

% Battary Usage in mAh
tENG.BATUSED = text(handle,46,-11.5,'----',...
    'FontSize',18,...
    'FontName','Agency FB',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','middle',...
    'Color','g');





hold(handle,'off')








end

